version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Allow Jenkins to communicate with Docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
    networks:
      - jenkins_network

  docker:
    image: docker:20.10.8-dind
    container_name: docker-dind
    privileged: true  # DinD requires privileged access
    volumes:
      - /var/lib/docker
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home:
